// <auto-generated />
using System;
using CrossFitWOD.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CrossFitWOD.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260331153423_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CrossFitWOD.Domain.Entities.Athlete", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");


                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float?>("Weight")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Athletes");
                });

            modelBuilder.Entity("CrossFitWOD.Domain.Entities.AthleteWorkout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    b.Property<int>("AthleteId")
                        .HasColumnType("integer");


                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<float>("ScaledRepsFactor")
                        .HasColumnType("real");

                    b.Property<int>("WorkoutSessionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutSessionId");

                    b.HasIndex("AthleteId", "WorkoutSessionId")
                        .IsUnique();

                    b.ToTable("AthleteWorkouts");
                });

            modelBuilder.Entity("CrossFitWOD.Domain.Entities.Wod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Wods");
                });

            modelBuilder.Entity("CrossFitWOD.Domain.Entities.WodExercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int>("Reps")
                        .HasColumnType("integer");

                    b.Property<int>("WodId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("WodId");

                    b.ToTable("WodExercises");
                });

            modelBuilder.Entity("CrossFitWOD.Domain.Entities.WorkoutResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    b.Property<int>("AthleteWorkoutId")
                        .HasColumnType("integer");

                    b.Property<bool>("Completed")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float?>("Rounds")
                        .HasColumnType("real");

                    b.Property<int>("Rpe")
                        .HasColumnType("integer");

                    b.Property<int?>("TimeSeconds")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AthleteWorkoutId")
                        .IsUnique();

                    b.ToTable("WorkoutResults");
                });

            modelBuilder.Entity("CrossFitWOD.Domain.Entities.WorkoutSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("WodId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("WodId");

                    b.HasIndex("Date")
                        .IsUnique();

                    b.ToTable("WorkoutSessions");
                });

            modelBuilder.Entity("CrossFitWOD.Domain.Entities.AthleteWorkout", b =>
                {
                    b.HasOne("CrossFitWOD.Domain.Entities.Athlete", "Athlete")
                        .WithMany("AthleteWorkouts")
                        .HasForeignKey("AthleteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CrossFitWOD.Domain.Entities.WorkoutSession", "WorkoutSession")
                        .WithMany("AthleteWorkouts")
                        .HasForeignKey("WorkoutSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Athlete");

                    b.Navigation("WorkoutSession");
                });

            modelBuilder.Entity("CrossFitWOD.Domain.Entities.WodExercise", b =>
                {
                    b.HasOne("CrossFitWOD.Domain.Entities.Wod", "Wod")
                        .WithMany("Exercises")
                        .HasForeignKey("WodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wod");
                });

            modelBuilder.Entity("CrossFitWOD.Domain.Entities.WorkoutResult", b =>
                {
                    b.HasOne("CrossFitWOD.Domain.Entities.AthleteWorkout", "AthleteWorkout")
                        .WithOne("Result")
                        .HasForeignKey("CrossFitWOD.Domain.Entities.WorkoutResult", "AthleteWorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AthleteWorkout");
                });

            modelBuilder.Entity("CrossFitWOD.Domain.Entities.WorkoutSession", b =>
                {
                    b.HasOne("CrossFitWOD.Domain.Entities.Wod", "Wod")
                        .WithMany("WorkoutSessions")
                        .HasForeignKey("WodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wod");
                });

            modelBuilder.Entity("CrossFitWOD.Domain.Entities.Athlete", b =>
                {
                    b.Navigation("AthleteWorkouts");
                });

            modelBuilder.Entity("CrossFitWOD.Domain.Entities.AthleteWorkout", b =>
                {
                    b.Navigation("Result");
                });

            modelBuilder.Entity("CrossFitWOD.Domain.Entities.Wod", b =>
                {
                    b.Navigation("Exercises");

                    b.Navigation("WorkoutSessions");
                });

            modelBuilder.Entity("CrossFitWOD.Domain.Entities.WorkoutSession", b =>
                {
                    b.Navigation("AthleteWorkouts");
                });
#pragma warning restore 612, 618
        }
    }
}
