// <auto-generated />
using System;
using CrossFitWOD.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CrossFitWOD.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260406184329_AddDailyLogsAndStatus")]
    partial class AddDailyLogsAndStatus
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CrossFitWOD.Entities.Athlete", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BoxId")
                        .HasColumnType("integer")
                        .HasColumnName("boxid");

                    b.Property<int>("CommitmentLevel")
                        .HasColumnType("integer")
                        .HasColumnName("commitmentlevel");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<int>("DaysPerWeek")
                        .HasColumnType("integer")
                        .HasColumnName("daysperweek");

                    b.Property<string>("Equipment")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("equipment");

                    b.Property<int>("Goal")
                        .HasColumnType("integer");

                    b.Property<string>("InjuryHistory")
                        .HasColumnType("text")
                        .HasColumnName("injuryhistory");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("SessionDurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("sessiondurationminute");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("userid");

                    b.Property<string>("WeakPoints")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("weekpoints");

                    b.Property<float?>("Weight")
                        .HasColumnType("real")
                        .HasColumnName("weight");

                    b.HasKey("Id");

                    b.HasIndex("BoxId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Athlete");
                });

            modelBuilder.Entity("CrossFitWOD.Entities.AthleteDailyLogs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AthleteId")
                        .HasColumnType("integer")
                        .HasColumnName("athleteid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<int>("EnergyLevel")
                        .HasColumnType("integer")
                        .HasColumnName("energylevel");

                    b.Property<int>("FatigueLevel")
                        .HasColumnType("integer")
                        .HasColumnName("fatiguelevel");

                    b.Property<string>("MentalState")
                        .HasColumnType("text")
                        .HasColumnName("mentalstate");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("PainNotes")
                        .HasColumnType("text")
                        .HasColumnName("painnotes");

                    b.Property<float?>("SleepHours")
                        .HasColumnType("real")
                        .HasColumnName("sleephours");

                    b.HasKey("Id");

                    b.HasIndex("AthleteId");

                    b.ToTable("AthleteDailyLogs");
                });

            modelBuilder.Entity("CrossFitWOD.Entities.AthleteStates", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AthleteId")
                        .HasColumnType("integer")
                        .HasColumnName("athleteid");

                    b.Property<float?>("BodyFat")
                        .HasColumnType("real")
                        .HasColumnName("bodyfat");

                    b.Property<float?>("MuscleMass")
                        .HasColumnType("real")
                        .HasColumnName("musclemass");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recordedat");

                    b.Property<float?>("Weight")
                        .HasColumnType("real")
                        .HasColumnName("weight");

                    b.HasKey("Id");

                    b.HasIndex("AthleteId");

                    b.ToTable("AthleteStates");
                });

            modelBuilder.Entity("CrossFitWOD.Entities.AthleteStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float>("AcuteLoad")
                        .HasColumnType("real")
                        .HasColumnName("acuteload");

                    b.Property<int>("AthleteId")
                        .HasColumnType("integer")
                        .HasColumnName("athleteid");

                    b.Property<float>("ChronicLoad")
                        .HasColumnType("real")
                        .HasColumnName("chronicload");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<float>("FatigueLevel")
                        .HasColumnType("real")
                        .HasColumnName("fatiguelevel");

                    b.Property<float>("FitnessLevel")
                        .HasColumnType("real")
                        .HasColumnName("fitnesslevel");

                    b.Property<string>("InjuryRisk")
                        .HasColumnType("text")
                        .HasColumnName("injuryrisk");

                    b.Property<float>("LastPerformanceScore")
                        .HasColumnType("real")
                        .HasColumnName("lastperformancescore");

                    b.Property<float>("LoadRatio")
                        .HasColumnType("real")
                        .HasColumnName("loadratio");

                    b.Property<string>("PerformanceTrend")
                        .HasColumnType("text")
                        .HasColumnName("performancetrend");

                    b.Property<string>("Readiness")
                        .HasColumnType("text")
                        .HasColumnName("readiness");

                    b.Property<float>("RecoveryScore")
                        .HasColumnType("real")
                        .HasColumnName("recoveryscore");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedat");

                    b.HasKey("Id");

                    b.HasIndex("AthleteId");

                    b.ToTable("AthleteStatus");
                });

            modelBuilder.Entity("CrossFitWOD.Entities.AthleteWorkout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AthleteId")
                        .HasColumnType("integer")
                        .HasColumnName("athleteid");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<float>("ScaledRepsFactor")
                        .HasColumnType("real")
                        .HasColumnName("scaledrepsfactor");

                    b.Property<int>("WorkoutSessionId")
                        .HasColumnType("integer")
                        .HasColumnName("workoutsessionid");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutSessionId");

                    b.HasIndex("AthleteId", "WorkoutSessionId")
                        .IsUnique();

                    b.ToTable("AthleteWorkout");
                });

            modelBuilder.Entity("CrossFitWOD.Entities.Box", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<bool>("IsIndividual")
                        .HasColumnType("boolean")
                        .HasColumnName("isindividual");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<DateTime?>("SubscriptionEndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("subscriptionendsat");

                    b.Property<string>("SubscriptionStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subscriptionstatus");

                    b.Property<DateTime?>("TrialEndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("trialendsat");

                    b.HasKey("Id");

                    b.ToTable("Box");
                });

            modelBuilder.Entity("CrossFitWOD.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BoxId")
                        .HasColumnType("integer")
                        .HasColumnName("boxid");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("passwordhash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("BoxId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("User");
                });

            modelBuilder.Entity("CrossFitWOD.Entities.Wod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("durationminutes");

                    b.Property<string>("Focus")
                        .HasColumnType("text")
                        .HasColumnName("focus");

                    b.Property<string>("Intensity")
                        .HasColumnType("text")
                        .HasColumnName("intensity");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("iddeleted");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tittle");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.ToTable("Wod");
                });

            modelBuilder.Entity("CrossFitWOD.Entities.WodExercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<int>("Reps")
                        .HasColumnType("integer")
                        .HasColumnName("reps");

                    b.Property<int>("WodId")
                        .HasColumnType("integer")
                        .HasColumnName("wodid");

                    b.HasKey("Id");

                    b.HasIndex("WodId");

                    b.ToTable("WodExercise");
                });

            modelBuilder.Entity("CrossFitWOD.Entities.WorkoutResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AthleteWorkoutId")
                        .HasColumnType("integer")
                        .HasColumnName("athleteworkoutid");

                    b.Property<bool>("Completed")
                        .HasColumnType("boolean")
                        .HasColumnName("completed");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("durationsecords");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<float?>("Rounds")
                        .HasColumnType("real")
                        .HasColumnName("rounds");

                    b.Property<int>("Rpe")
                        .HasColumnType("integer")
                        .HasColumnName("rpe");

                    b.Property<int?>("TimeSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("timesecords");

                    b.HasKey("Id");

                    b.HasIndex("AthleteWorkoutId")
                        .IsUnique();

                    b.ToTable("workoutresult");
                });

            modelBuilder.Entity("CrossFitWOD.Entities.WorkoutSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BoxId")
                        .HasColumnType("integer")
                        .HasColumnName("boxid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<int>("WodId")
                        .HasColumnType("integer")
                        .HasColumnName("wodid");

                    b.HasKey("Id");

                    b.HasIndex("WodId");

                    b.HasIndex("BoxId", "Date")
                        .IsUnique();

                    b.ToTable("WorkoutSession");
                });

            modelBuilder.Entity("CrossFitWOD.Entities.Athlete", b =>
                {
                    b.HasOne("CrossFitWOD.Entities.Box", "Box")
                        .WithMany("Athletes")
                        .HasForeignKey("BoxId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CrossFitWOD.Entities.User", "User")
                        .WithOne()
                        .HasForeignKey("CrossFitWOD.Entities.Athlete", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Box");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CrossFitWOD.Entities.AthleteDailyLogs", b =>
                {
                    b.HasOne("CrossFitWOD.Entities.Athlete", "Athlete")
                        .WithMany("DailyLogs")
                        .HasForeignKey("AthleteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Athlete");
                });

            modelBuilder.Entity("CrossFitWOD.Entities.AthleteStates", b =>
                {
                    b.HasOne("CrossFitWOD.Entities.Athlete", "Athlete")
                        .WithMany("PhysicalLogs")
                        .HasForeignKey("AthleteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Athlete");
                });

            modelBuilder.Entity("CrossFitWOD.Entities.AthleteStatus", b =>
                {
                    b.HasOne("CrossFitWOD.Entities.Athlete", "Athlete")
                        .WithMany("Statuses")
                        .HasForeignKey("AthleteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Athlete");
                });

            modelBuilder.Entity("CrossFitWOD.Entities.AthleteWorkout", b =>
                {
                    b.HasOne("CrossFitWOD.Entities.Athlete", "Athlete")
                        .WithMany("AthleteWorkouts")
                        .HasForeignKey("AthleteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CrossFitWOD.Entities.WorkoutSession", "WorkoutSession")
                        .WithMany("AthleteWorkouts")
                        .HasForeignKey("WorkoutSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Athlete");

                    b.Navigation("WorkoutSession");
                });

            modelBuilder.Entity("CrossFitWOD.Entities.User", b =>
                {
                    b.HasOne("CrossFitWOD.Entities.Box", "Box")
                        .WithMany("Users")
                        .HasForeignKey("BoxId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Box");
                });

            modelBuilder.Entity("CrossFitWOD.Entities.WodExercise", b =>
                {
                    b.HasOne("CrossFitWOD.Entities.Wod", "Wod")
                        .WithMany("Exercises")
                        .HasForeignKey("WodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wod");
                });

            modelBuilder.Entity("CrossFitWOD.Entities.WorkoutResult", b =>
                {
                    b.HasOne("CrossFitWOD.Entities.AthleteWorkout", "AthleteWorkout")
                        .WithOne("Result")
                        .HasForeignKey("CrossFitWOD.Entities.WorkoutResult", "AthleteWorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AthleteWorkout");
                });

            modelBuilder.Entity("CrossFitWOD.Entities.WorkoutSession", b =>
                {
                    b.HasOne("CrossFitWOD.Entities.Box", "Box")
                        .WithMany()
                        .HasForeignKey("BoxId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CrossFitWOD.Entities.Wod", "Wod")
                        .WithMany("WorkoutSessions")
                        .HasForeignKey("WodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Box");

                    b.Navigation("Wod");
                });

            modelBuilder.Entity("CrossFitWOD.Entities.Athlete", b =>
                {
                    b.Navigation("AthleteWorkouts");

                    b.Navigation("DailyLogs");

                    b.Navigation("PhysicalLogs");

                    b.Navigation("Statuses");
                });

            modelBuilder.Entity("CrossFitWOD.Entities.AthleteWorkout", b =>
                {
                    b.Navigation("Result");
                });

            modelBuilder.Entity("CrossFitWOD.Entities.Box", b =>
                {
                    b.Navigation("Athletes");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("CrossFitWOD.Entities.Wod", b =>
                {
                    b.Navigation("Exercises");

                    b.Navigation("WorkoutSessions");
                });

            modelBuilder.Entity("CrossFitWOD.Entities.WorkoutSession", b =>
                {
                    b.Navigation("AthleteWorkouts");
                });
#pragma warning restore 612, 618
        }
    }
}
